import { Queue, Worker, type Job } from 'bullmq';
import { redisForQueues } from '../config/redis';
import { prisma } from '../config/database';
import { withTenantSchema } from '../lib/prisma';
import { logger } from '../lib/logger';
import { email as emailClient } from '../lib/email';

const QUEUE_NAME = 'scheduled-reports';

export const scheduledReportsQueue = new Queue(QUEUE_NAME, {
  connection: redisForQueues,
  defaultJobOptions: { attempts: 3, backoff: { type: 'exponential', delay: 15_000 } },
});

// Runs every 5 minutes and dispatches any due reports
export async function scheduleReportsJob(): Promise<void> {
  await scheduledReportsQueue.add(
    'check-due-reports',
    {},
    {
      jobId: 'scheduled-reports-poll',
      repeat: { pattern: '*/5 * * * *' },
      removeOnComplete: 5,
      removeOnFail: 10,
    },
  );
}

interface TenantRow {
  id: string;
  schema_name: string;
  name: string;
}

async function getAllActiveTenants(): Promise<TenantRow[]> {
  return prisma.$queryRaw<TenantRow[]>`
    SELECT id, schema_name, name
    FROM global.tenants
    WHERE is_active = TRUE AND deleted_at IS NULL
  `;
}

interface DueReport {
  id: string;
  name: string;
  frequency: string;
  day_of_week: number | null;
  day_of_month: number | null;
  hour: number;
  recipients: string[];
  format: string;
  next_run_at: Date | null;
}

function computeNextRun(
  frequency: string,
  hour: number,
  dayOfWeek: number | null,
  dayOfMonth: number | null,
): Date {
  const now = new Date();
  const next = new Date(now);
  next.setSeconds(0);
  next.setMilliseconds(0);

  if (frequency === 'daily') {
    next.setHours(hour, 0, 0, 0);
    if (next <= now) next.setDate(next.getDate() + 1);
  } else if (frequency === 'weekly') {
    const dow = dayOfWeek ?? 1;
    next.setHours(hour, 0, 0, 0);
    const diff = (dow - next.getDay() + 7) % 7;
    next.setDate(next.getDate() + (diff === 0 && next <= now ? 7 : diff));
  } else if (frequency === 'monthly') {
    const dom = dayOfMonth ?? 1;
    next.setHours(hour, 0, 0, 0);
    next.setDate(dom);
    if (next <= now) {
      next.setMonth(next.getMonth() + 1);
      next.setDate(dom);
    }
  }

  return next;
}

async function processTenantReports(tenant: TenantRow): Promise<void> {
  const dueReports = await withTenantSchema(tenant.schema_name, async (prismaClient) => {
    return prismaClient.$queryRawUnsafe<DueReport[]>(`
      SELECT id, name, frequency, day_of_week, day_of_month, hour, recipients, format, next_run_at
      FROM scheduled_reports
      WHERE is_active = true
        AND (next_run_at IS NULL OR next_run_at <= NOW())
    `).catch(() => [] as DueReport[]);
  });

  for (const report of dueReports) {
    try {
      // Lazy import to avoid circular deps at startup
      const { generateExecutivePdf, generateExecutiveExcel } = await import('../modules/reports/reports.service');

      const attachments: Array<{ filename: string; content: Buffer; contentType: string }> = [];

      if (report.format === 'pdf' || report.format === 'both') {
        const buf = await generateExecutivePdf(tenant.schema_name, {});
        attachments.push({ filename: `${tenant.name}-compliance-report.pdf`, content: buf, contentType: 'application/pdf' });
      }
      if (report.format === 'excel' || report.format === 'both') {
        const buf = await generateExecutiveExcel(tenant.schema_name, {});
        attachments.push({ filename: `${tenant.name}-compliance-report.xlsx`, content: buf, contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
      }

      // Send to each recipient
      for (const recipientEmail of report.recipients) {
        await emailClient.sendRawEmail({
          to: recipientEmail,
          subject: `[ComplianceCore] ${report.name} — ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}`,
          html: `<p>Please find attached your scheduled compliance report: <strong>${report.name}</strong>.</p><p>Generated by ComplianceCore on ${new Date().toUTCString()}.</p>`,
          attachments,
        }).catch((err: unknown) => logger.warn({ err, recipientEmail }, 'Failed to send scheduled report email'));
      }

      const nextRun = computeNextRun(report.frequency, report.hour, report.day_of_week, report.day_of_month);

      await withTenantSchema(tenant.schema_name, async (prismaClient) => {
        await prismaClient.$queryRawUnsafe(
          `UPDATE scheduled_reports SET last_run_at = NOW(), last_run_status = 'success', next_run_at = $1, updated_at = NOW() WHERE id = $2`,
          nextRun.toISOString(),
          report.id,
        );
      });

      logger.info({ reportId: report.id, tenantId: tenant.id }, 'Scheduled report sent');
    } catch (err) {
      logger.error({ err, reportId: report.id, tenantId: tenant.id }, 'Failed to process scheduled report');
      await withTenantSchema(tenant.schema_name, async (prismaClient) => {
        await prismaClient.$queryRawUnsafe(
          `UPDATE scheduled_reports SET last_run_status = 'failed', updated_at = NOW() WHERE id = $1`,
          report.id,
        ).catch(() => undefined);
      });
    }
  }
}

async function runCheck(): Promise<void> {
  const tenants = await getAllActiveTenants();
  logger.info({ count: tenants.length }, 'Checking scheduled reports for all tenants');
  for (const tenant of tenants) {
    try {
      await processTenantReports(tenant);
    } catch (err) {
      logger.error({ err, tenantId: tenant.id }, 'Scheduled report check failed for tenant');
    }
  }
}

export function startScheduledReportsWorker(): Worker {
  const worker = new Worker(QUEUE_NAME, async (_job: Job) => {
    await runCheck();
  }, { connection: redisForQueues, concurrency: 1 });

  worker.on('completed', () => logger.info('Scheduled reports check completed'));
  worker.on('failed', (job, err) => logger.error({ jobId: job?.id, err }, 'Scheduled reports job failed'));

  return worker;
}
