-- 010_pricing_ngn_2026.sql
--
-- INTENTIONALLY A NO-OP. Kept so the migration version stays recorded on
-- databases where an earlier version of this file already ran.
--
-- This file used to set the naira prices and insert the Business tier by
-- writing to global.subscription_plans. That table is NOT created by the
-- migration runner — it is created lazily by initBillingTables() in
-- src/modules/billing/billing.repository.ts when the app boots, and every
-- migration runs BEFORE the app starts (see railway.json's
-- `migrate.mjs && server.js`). So on a fresh database this failed with:
--
--   relation "global.subscription_plans" does not exist
--
-- which is precisely the trap 007 documents. It passed against production,
-- where a previous boot had already created the table, and broke CI on every
-- clean database — so the failure only showed up as a red build, four
-- deployments in a row, after the code had already been pushed.
--
-- The pricing correction now lives in initBillingTables() as a one-time,
-- marker-guarded block, where subscription_plans is guaranteed to exist.

SELECT 1;
